echo -e '\e[40m\e[92m'
echo -e '                                                   '
echo -e '  /$$$$$$                                          '
echo -e ' /$$__  $$                                         '
echo -e '| $$  \__/                                         '
echo -e '| $$ /$$$$|                                        '
echo -e '| $$|_  $$|                                        '
echo -e '| $$  \ $$|                                        '
echo -e '|  $$$$$$/|                                        '
echo -e ' \______/                                          '
echo -e '                                                   '
echo -e '\e[0m'